[2022-04-30T10:54:24.170338+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T10:54:24.172980+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T10:54:24.172986+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T10:54:24.172992+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T10:54:24.172994+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T10:54:24.173000+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T10:54:24.214703+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2022-04-30T11:58:53.795845+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T11:58:53.798840+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T11:58:53.798847+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T11:58:53.798853+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T11:58:53.798855+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T11:58:53.798861+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T11:58:53.827165+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2022-04-30T15:24:56.875280+03:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T15:24:56.880340+03:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T15:24:56.880347+03:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T15:24:56.880351+03:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T15:24:56.880353+03:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T15:24:56.880358+03:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T15:24:56.892413+03:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2022-04-30T12:25:12.724740+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T12:25:12.729840+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T12:25:12.729846+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T12:25:12.729851+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T12:25:12.729853+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T12:25:12.729859+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T12:25:12.741582+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2022-04-30T12:40:24.836897+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T12:40:24.841869+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T12:40:24.841875+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T12:40:24.841879+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T12:40:24.841881+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T12:40:24.841887+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T12:40:24.853467+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
